# Generated by Django 4.2.7 on 2026-02-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_time_end',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_time_start',
            field=models.TimeField(default='09:00'),
        ),
    ]
