# Generated by Django 5.2.9 on 2026-02-09 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctorprofile_available_time_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_file', models.FileField(upload_to='medical_reports/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report_date', models.DateField(help_text='Date of the medical report')),
                ('description', models.TextField(blank=True, help_text='Brief description of the report')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='accounts.patientprofile')),
            ],
            options={
                'verbose_name': 'Medical Report',
                'verbose_name_plural': 'Medical Reports',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
