# Generated by Django 5.2.9 on 2026-02-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_medicalreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalReport',
        ),
    ]
